version: '3.8'
services:
  app:
    image: orbital-ei
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app        # Mount current directory
      - /usr/src/app/node_modules  # Prevent overwriting node_modules
    command: npm run dev      # Override CMD to use development mode
    depends_on:
      - db
    environment:
      - DB_USER=${DB_USER}
      - DB_HOST=db        # Explicitly set this to override .env
      - DB_NAME=${DB_NAME}
      - DB_PSWD=${DB_PSWD}
      - DB_PORT=${DB_PORT}
    env_file:
      - .env

  db:
    image: postgis/postgis
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PSWD}
      - POSTGRES_DB=${DB_NAME}
    env_file:
      - .env
    volumes:
      - ./src/migrations/init.sql:/docker-entrypoint-initdb.d/init.sql